{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "my-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      path: {{ .Values.monitoring.serviceMonitor.path }}
      scheme: http
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: (.*)
          targetLabel: node
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_name]
          separator: ;
          regex: (.*)
          targetLabel: pod
          replacement: $1
          action: replace
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "my-app.fullname" . }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
spec:
  groups:
    - name: {{ include "my-app.fullname" . }}.rules
      rules:
        - alert: HighErrorRate
          expr: |
            sum(rate(http_requests_total{job="{{ include "my-app.fullname" . }}", status=~"5.."}[5m]))
            /
            sum(rate(http_requests_total{job="{{ include "my-app.fullname" . }}"}[5m])) > 0.1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: High HTTP error rate
            description: More than 10% of requests are failing with 5xx errors

        - alert: HighLatency
          expr: |
            histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="{{ include "my-app.fullname" . }}"}[5m])) by (le)) > 2
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High latency
            description: 95th percentile latency is above 2 seconds

        - alert: HighCPUUsage
          expr: |
            sum(rate(container_cpu_usage_seconds_total{container="{{ include "my-app.fullname" . }}"}[5m])) by (pod)
            /
            sum(container_spec_cpu_quota{container="{{ include "my-app.fullname" . }}"}) by (pod) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High CPU usage
            description: Container is using more than 80% of its CPU quota

        - alert: HighMemoryUsage
          expr: |
            sum(container_memory_usage_bytes{container="{{ include "my-app.fullname" . }}"}) by (pod)
            /
            sum(container_spec_memory_limit_bytes{container="{{ include "my-app.fullname" . }}"}) by (pod) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High memory usage
            description: Container is using more than 80% of its memory limit
{{- end }}
