# Backup Configuration
backup:
  enabled: true
  schedule: "0 1 * * *"  # Daily at 1 AM
  ttl: 720h  # 30 days
  bucket: "my-app-backups"
  region: "us-west-2"

# Security Configuration
security:
  enabled: true
  auth:
    issuer: "auth.example.com"
  allowedEgressCIDR: "0.0.0.0/0"
  
  # Pod Security Policy
  psp:
    enabled: true
  
  # Certificate Management
  certificates:
    enabled: true
    renewBefore: 360h  # 15 days
    duration: 2160h    # 90 days

# Advanced Monitoring
monitoring:
  grafana:
    dashboards:
      enabled: true
      label: grafana_dashboard
  
  # Distributed Tracing
  jaeger:
    enabled: true
    collector:
      service:
        type: ClusterIP
    agent:
      strategy: DaemonSet
    
  # Logging
  elasticsearch:
    enabled: true
    replicas: 3
    persistence:
      size: 100Gi
  
  kibana:
    enabled: true
    service:
      type: ClusterIP
  
  filebeat:
    enabled: true
    config:
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

# Disaster Recovery
dr:
  enabled: true
  # Cross-Region Replication
  replication:
    enabled: true
    targetRegion: "us-east-1"
    syncInterval: "1h"
  
  # Failover Configuration
  failover:
    enabled: true
    automaticFailover: true
    healthCheck:
      enabled: true
      interval: "30s"
      timeout: "5s"
      successThreshold: 1
      failureThreshold: 3

# Advanced Deployment Strategies
deployment:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  
  # Canary Deployment
  canary:
    enabled: true
    steps:
      - weight: 20
        pause: 5m
      - weight: 40
        pause: 5m
      - weight: 60
        pause: 5m
      - weight: 80
        pause: 5m
      - weight: 100
        pause: 5m
  
  # Blue-Green Deployment
  blueGreen:
    enabled: true
    autoPromote: false
    activeService: blue
    previewService: green
    
  # Progressive Delivery
  progressiveDelivery:
    enabled: true
    analysis:
      interval: 30s
      maxPhase: 10
      metrics:
        - name: request-success-rate
          interval: 1m
          successCondition: result[0] >= 0.95
          failureCondition: result[0] < 0.95
        - name: request-duration
          interval: 1m
          successCondition: result[0] <= 500
          failureCondition: result[0] > 500

# Service Mesh Advanced Configuration
istio:
  mtls:
    mode: STRICT
  
  # Circuit Breaking
  circuitBreaker:
    enabled: true
    consecutive5xxErrors: 5
    interval: "30s"
    baseEjectionTime: "30s"
    maxEjectionPercent: 10
  
  # Rate Limiting
  rateLimit:
    enabled: true
    requestsPerUnit: 1000
    unit: MINUTE
