apiVersion: v2
name: my-app
description: A Helm chart for the Khayelihle System Frontend
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: DevOps Team
    email: devops@example.com

dependencies:
  - name: postgresql
    version: "12.1.3"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.3.14"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: "19.5.8"
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: prometheus
    version: "19.6.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: cert-manager
    version: "v1.11.0"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
