# Advanced Testing Configuration
testing:
  enabled: true
  e2e:
    schedule: "*/30 * * * *"  # Every 30 minutes
    cypress:
      version: "12.3.0"
      video: true
      screenshots: true
  performance:
    schedule: "0 */2 * * *"  # Every 2 hours
    k6:
      stages:
        - duration: 5m
          target: 100
        - duration: 10m
          target: 100
        - duration: 5m
          target: 0
      thresholds:
        http_req_duration: "p(95)<500"
        http_req_failed: "rate<0.01"
  security:
    schedule: "0 0 * * *"  # Daily
    zap:
      fullScan: false
      apis: true
      spiderAjax: true

# Advanced Monitoring Configuration
monitoring:
  metrics:
    performance:
      enabled: true
      pageLoadTime: true
      firstContentfulPaint: true
      largestContentfulPaint: true
      firstInputDelay: true
      cumulativeLayoutShift: true
    errors:
      enabled: true
      trackJsExceptions: true
      trackApiErrors: true
    resources:
      enabled: true
      trackMemory: true
      trackCPU: true
    userExperience:
      enabled: true
      trackSessionDuration: true
      trackBounceRate: true
    business:
      enabled: true
      trackConversions: true
      trackRevenue: true
  alerts:
    performance:
      pageLoadTimeThreshold: 3
      errorRateThreshold: 0.05
    resources:
      memoryThreshold: 80
      cpuThreshold: 80
    business:
      bounceRateThreshold: 0.6

# GitOps Configuration
gitops:
  enabled: true
  repository: "https://github.com/your-org/your-repo.git"
  branch: "main"
  notifications:
    slack:
      enabled: true
      channel: "#deployments"
  automation:
    prune: true
    selfHeal: true
  syncInterval: "5m"
  validation:
    enabled: true
    timeout: "5m"

# Advanced Security Configuration
security:
  networkPolicies:
    defaultDeny: true
    allowedNamespaces:
      - kube-system
      - monitoring
      - logging
  podSecurityPolicies:
    enabled: true
    enforcePrivileged: false
  secretsManagement:
    vault:
      enabled: true
      path: "secret/data/my-app"
  authentication:
    oidc:
      enabled: true
      issuer: "https://auth.example.com"
      clientId: "my-app"
  authorization:
    rbac:
      enabled: true
      roles:
        - name: reader
          rules:
            - apiGroups: [""]
              resources: ["pods", "services"]
              verbs: ["get", "list", "watch"]
        - name: editor
          rules:
            - apiGroups: [""]
              resources: ["pods", "services"]
              verbs: ["*"]
  scanning:
    enabled: true
    schedule: "0 0 * * *"
    failOnHigh: true
    tools:
      - trivy
      - snyk
      - clair

# Progressive Delivery Configuration
delivery:
  strategy: canary
  analysis:
    interval: "30s"
    maxPhase: 10
    metrics:
      - name: request-success-rate
        interval: 1m
        successCondition: result[0] >= 0.95
        failureCondition: result[0] < 0.95
      - name: request-duration
        interval: 1m
        successCondition: result[0] <= 500
        failureCondition: result[0] > 500
  rollback:
    enabled: true
    limit: 5
    trigger:
      metrics:
        - name: error-rate
          threshold: 0.05
        - name: latency-p95
          threshold: 500
  promotion:
    auto: false
    requireApproval: true
    approvers:
      - team-leads
      - devops-team
